### PR TITLE
Use nullable long for queue info

### PR DESCRIPTION
**Pull request by RackovychV**
Sometimes when rabbitmq nodes in sync state, messages param not specified in json. In rabbitmq ui such queues showed with NAN messages count.
So I suggest using nullable Long fields in QueueInfo

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@RackovychV Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=224)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=224) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by michaelklishin** [comment]
This looks reasonable. It is true that queue processes can only emit a subset of stats in some states. @acogoluegnes WDYT?

**Comment by acogoluegnes** [comment]
I'm not super comfortable with the change because it feels like a breaking one, even though I can't see any scenarios when autoboxing and unboxing could break.

What's the current behavior when those fields are NaN @RackovychV? Does Jackson freak out?

An alternative would be to keep the primitive longs and use a custom deserializer. The NaN value would be -1, which makes sense for all the fields I think (they can't be negative).

**Comment by RackovychV** [comment]
When ui showed NAN messages count, such fields not present in json response. Therefore QueueInfo fields leaved with default value 0.
I agree that now it's breaking change. Maybe -1 will be better.
So fields initialization with -1 will solve the issue. Even without cusom deserializer.

**Comment by acogoluegnes** [comment]
0 is definitely not a good value for NaN. Maybe just setting `@JsonProperty(value = "disk_reads", defaultValue = "-1")` for those fields would do the trick.

**Comment by michaelklishin** [comment]
@RackovychV do you agree with @acogoluegnes' suggestion? If so, would you have time to follow-up on this PR? Thank you!

**Pull request closed without merging**
