### PR TITLE
Curated classpath integration test

### PR DESCRIPTION
**Pull request by kubamarchwicki**
A separate test task for each available http client, to check cross-client classpath dependencies.

### CODE REVIEW

**Comment by acogoluegnes** [comment]
Is it ready for review (still marked as a draft)?

OK, so there was a dependency on HttpComponents in `Client` because of the no-op configurator, this would make HttpComponents necessary even if it's not used, right?

Note the project will migrate from Gradle to Maven anytime soon, not sure we run isolated tests like those with Maven.

**Comment by acogoluegnes** [comment]
Do we need to launch a specific task for each of these tests? If so, we could do pretty much the same with Maven profiles. We would just need to launch Maven several times, one for each test.

**Comment by kubamarchwicki** [comment]
> Is it ready for review (still marked as a draft)?

I tend not to submit things too late at night :) And I want to amend the readme. Will finalize it later today.

> OK, so there was a dependency on HttpComponents in Client because of the no-op configurator, this would make HttpComponents necessary even if it's not used, right?

Right!

> Note the project will migrate from Gradle to Maven anytime soon, not sure we run isolated tests like those with Maven.

It might be possible through failsafe and profiles - but I'll need to have a look. Other things interest me: why migrating from gradle to maven. Out of curiosity, I'm not opinionated about either of these :)

**Comment by kubamarchwicki** [comment]
> Do we need to launch a specific task for each of these tests? If so, we could do pretty much the same with Maven profiles. We would just need to launch Maven several times, one for each test.

These should run automatically before actual tests as separate tasks

**Comment by acogoluegnes** [comment]
Gradle is overkill for a simple project like Hop, even though what you've just added here kinda proves me wrong.

Nevertheless, it brought us more trouble than it's worth over the last few years, one example being the [incompatibility on Java 14](https://github.com/gradle/gradle/issues/10248), so the impossibility of testing the library on Java 14 (which is due in a couple of months). We made the test suite run on our CI by automatically generating and tweaking a `pom.xml` file to launch it with Maven on Java 14 (and 15). This is a bit crazy to test a library on the latest builds of Java.

**Comment by acogoluegnes** [comment]
FYI, I'm hacking around to see if Hop could run only with the JDK utilities. The test suite seems to succeed so far. This may require a bit of work and testing to make sure everything is fine on TLS as well.

**Comment by jakubmarchwicki** [comment]
> FYI, I'm hacking around to see if Hop could run only with the JDK utilities. The test suite seems to succeed so far. This may require a bit of work and testing to make sure everything is fine on TLS as well.

Do you mean the native [JDK http client](https://openjdk.java.net/groups/net/httpclient/intro.html)? It's an incubating model since JDK9 with official support in JDK11. I'm not sure if having JDK11 as a requirement (as opposed to the current JDK8) is something users will happy about

**Comment by acogoluegnes** [comment]
@jakubmarchwicki No, I mean the historical JDK HTTP facilities (`HttpURLConnection`), based on `SimpleClientHttpRequestFactory`.

There's no `ClientHttpRequestFactory` implementation for Java 11 HTTP client, but that could be done without requiring Java 11 for Hop (as long as this very implementation is not used).

**Comment by kubamarchwicki** [comment]
@acogoluegnes got it! The default implementation of [feign client](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Client.java#L59) is based on JDK HTTP facilities. 
I'm not sure if `feign` itself is a good abstraction or maybe it's possible to postpone this decision until people will be ready for JDK11: there will be a better abstraction than `HttpURLConnection` and people will have choices (based on Spring's abstraction).

**Comment by acogoluegnes** [comment]
Thanks!

**Comment by acogoluegnes** [comment]
> @acogoluegnes got it! The default implementation of [feign client](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Client.java#L59) is based on JDK HTTP facilities.
> I'm not sure if `feign` itself is a good abstraction or maybe it's possible to postpone this decision until people will be ready for JDK11: there will be a better abstraction than `HttpURLConnection` and people will have choices (based on Spring's abstraction).

Hop supports the 3 libraries that `RestTemplate` supports and this stays pluggable, so I guess we're fine for now. I'd be happy to make the JDK facilities the default to make people's life easier with dependencies. Honestly I don't know what the other implementations brings in the case of Hop, because they're called through an abstraction and using their API is only necessary for configuration.

**Pull request merged**
