### PR TITLE
Create enum for binding-type

### PR DESCRIPTION
**Pull request by kurenchuksergey**
as a simple user, I want to have the possibility filter bindings without magic strings

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kurenchuksergey Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=220)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=220) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kurenchuksergey Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=220)!

**Comment by kurenchuksergey** [comment]
@acogoluegnes fixed

**Comment by acogoluegnes** [comment]
Thanks!

**Pull request merged**
