### PR TITLE
Add effective_policy_definition to QueueInfo

### PR DESCRIPTION
**Pull request by ifyun**
References #460

### CODE REVIEW

**Comment by acogoluegnes** [comment]
@ifyun Thanks for the contribution. The changes look good, but could you re-submit the PR _without_ the formatting changes? They are huge and unnecessary, and it makes the actual changes very hard to spot. Thanks.

**Comment by ifyun** [comment]
Update to the correct format.

**Comment by acogoluegnes** [comment]
Why did you add `policyInfo` with `@JsonIgnore`?

**Comment by ifyun** [comment]
> Why did you add `policyInfo` with `@JsonIgnore`?

`policyInfo` does not appear in the HTTP response, but I found that it could be injected into `QueueInfo` with `priority`, so I added this field with `@JsonIgnore`

**Comment by ifyun** [comment]
I got mixed up, there shouldn't be a `policyInfo` field.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you.

**Pull request merged**
