### PR TITLE
Make the project compatible with Bamboo CI

### PR DESCRIPTION
**Pull request by artembilan**
* polishing for `build.gradle`
* add `publish-maven.gradle` to generate correct `POM`
* change Gradle to `ALL` distribution (includes sources)
* Make JavaDocs in Java 8 and Spring style
* Add Apache License `@Copyright` for all classes
* Add `license.txt` and `notice.txt`
* `@Ignore` `"PUT /api/vhosts/{name}"` Sock Spec as it doesn't pass with non-latin symbols

### CODE REVIEW

**Comment by michaelklishin** [comment]
Interesting. Creation of vhosts does pass for me (OS X Yosemite) with non-ASCII characters. What OS and JDK do you observe failures with?

**Comment by artembilan** [comment]
Hi @michaelklishin !

Windows 7 x64, Java 8, RabbitMQ 3.4.3

**Comment by artembilan** [comment]
Failed with
> 500 Internal Server Error

On the `client.getVhost(name)` for non-ASCII, yes.

**Comment by michaelklishin** [comment]
Got it. We'll use [conditional ignores](http://mrhaki.blogspot.ru/2014/06/spocklight-ignore-specifications-based.html) then and investigate.

**Comment by artembilan** [comment]
`@IgnoreIf({ isOsWindows() })` :smile:

**Comment by michaelklishin** [comment]
Thank you. Waiting for the Travis build to finish and merging if it goes well.

**Comment by artembilan** [comment]
Good. Although pay attention, please, to the `license.txt`, `notice.txt` and `overview.html`.
To have JavaDocs in that style our CI plan must use Java 8.

BTW, shouldn't we still support Java 6?
I see diamonds in your code, hence it is Java 7 already.

**Comment by artembilan** [comment]
And `gradle.properties`. As you see I changed version to `1.0.0.BUILD-SNAPSHOT`. Does that follow with your rules ?

**Comment by michaelklishin** [comment]
I was under the impression that Spring 4.x requires JDK 7? We can add JDK 6 support if needed. RabbitMQ Java client does support JDK 6.

**Comment by michaelklishin** [comment]
The version change is fine. We don't publish snapshots for the Java client (we'd like to), only have nightly builds. This versioning scheme is fine with us.

**Comment by artembilan** [comment]
No, SF 4 still supports Java 6.
Let me find and send you Juergen's monolog on the matter.

**Comment by michaelklishin** [comment]
No need. The diamond operator is probably the only 7-specific feature we have. Feel free to get rid of it, we are OK with supporting 6 as long as Spring does.

**Comment by artembilan** [comment]
Hey!
You've already merged it!

So, I need one more PR for Java 6 support and `@IgnoreIf({ isOsWindows() })`

**Comment by michaelklishin** [comment]
Sorry, didn't realise you wanted to push more changes. Feel free to submit another one :)

**Comment by garyrussell** [comment]
Just because Spring still support Java 6 doesn't mean we have to force this client to. Spring AMQP probably won't have any hard dependencies.

OTOH, if it's only `<>` then I guess there's no harm.

**Comment by michaelklishin** [comment]
I generally agree with Artem that JDK 6 is still worth supporting, especially since our Java client does just that, and it is included into our commercial support offering.

7 doesn't offer much for this particular library or RabbitMQ Java client.

**Pull request merged**
