### PR TITLE
 add source and destination exchange key for shovel details

### PR DESCRIPTION
**Pull request by sparcv9**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sparcv9 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=130)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=130) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sparcv9 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/hop&pullRequestId=130)!

**Comment by michaelklishin** [comment]
@acogoluegnes FYI.

**Comment by michaelklishin** [comment]
@sparcv9 thank you!

**Pull request merged**
