### PR TITLE
GH-85: Upgrade to Gradle 3.1

### PR DESCRIPTION
**Pull request by artembilan**
Fixes: GH-85 (https://github.com/rabbitmq/hop/issues/85)

### CODE REVIEW

**Comment by artembilan** [comment]
The `gradlew(.bat)` files are auto-generated by Gradle. Don't pay attention to them.

Interesting observation in the `/build/reports/jacoco/html` after running `gradlew test`.
I guess that is something new in Gradle and can help us somehow in other projects.
/cc @garyrussell .

Let's do not merge this until we receive a confirmation from @trevormarshall that we have RabbitMQ Broker already on Bamboo!

Meanwhile let me tweak Travis config as well!
Looks like the latest Sonar Cube isn't compatible with Java < 8.
Although who cares? We compile against Java 8 and produce artifact compatible even with Java 6.
Any objection to still have build against Java 7 ?

**Comment by trevormarshall** [comment]
management and MQTT plugins have been enabled in Bamboo CI.

**Comment by artembilan** [comment]
Well, now my hacking has made the Travis build as green :wink: and thanks to @trevormarshall we now have RabbitMQ on the CI server.
So, it is ready to merge :smile:

**Comment by michaelklishin** [comment]
Thank you very much @artembilan and @trevormarshall.

**Pull request merged**
