### PR TITLE
Add support for OkHttp in synchronous client

### LINKED ISSUE #205: Support for different httpclients to apache http-client
`hop` is currently using `apache httpclient` as the default implementation for handling HTTP traffic. However, as it uses `RestTemplate` as the main abstraction, it's possible to add other transport libraries (like okhttp) in a transparent manner.

## Rationale
When using `hop` in different environments, the choice of actual http client is usually opinionated and followed by a set of configurations and metrics. Adding `httpclient` together with `hop` may require (for example) an additional level explicit of configuration. I strongly believe a choice of the underlying http client should be transparent for a utility library like `hop`.

### PR DESCRIPTION
**Pull request by acogoluegnes**
Following up on #206.

Fixes #205.

### CODE REVIEW

**Comment by kubamarchwicki** [comment]
I've made a small experiment and run the current configuration without any httpclient on the classpath (neither apache nor okhttp) - utilizing spring and spring's `SimpleClientHttpRequestFactory`. To my surprise it nearly worked out (a jshell snippet below)

```java
import org.springframework.http.client.*;
import com.rabbitmq.http.client.*;
import org.springframework.http.client.support.*;

var url = "http://guest:guest@localhost:15672/api";
var params = new ClientParameters().url(url).restTemplateConfigurator(ctx -> {
    var rt = ctx.getRestTemplate(); 
    rt.setInterceptors(List.of(new BasicAuthenticationInterceptor(ctx.getClientParameters().getUsername(), ctx.getClientParameters().getPassword()))); 
    rt.setRequestFactory(new SimpleClientHttpRequestFactory()); 
    return rt;
    });
var client = new Client(params);
client.getNodes()
client.getUsers()
```

I'm not sure if that's in scope - but it the change you've made opened pretty nice possibilities: an option of http client *implementation that uses standard JDK facilities*. If you thinks is an idea to follow, I can try to refactor that, keeping the backwards compatibility. The only bit is a direct dependency on `apache httpclient` in `Client` class - I believe

The complete classpath to run the above snippet is `jshell --class-path build/libs/http-client-3.6.0.BUILD-SNAPSHOT.jar:~/.m2/repository/org/springframework/spring-web/5.2.1.RELEASE/spring-web-5.2.1.RELEASE.jar:~/.m2/repository/org/springframework/spring-core/5.2.1.RELEASE/spring-core-5.2.1.RELEASE.jar:~/.m2/repository/org/springframework/spring-beans/5.2.1.RELEASE/spring-beans-5.2.1.RELEASE.jar:~/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.10.1/jackson-core-2.10.1.jar:~/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.10.1/jackson-annotations-2.10.1.jar:~/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.10.1/jackson-databind-2.10.1.jar:~/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar`

**Comment by acogoluegnes** [comment]
@kubamarchwicki Feel free to experiment and submit a PR with your findings. Start from the top of the `master` branch, I merged this PR and pushed a few small changes.

**Comment by michaelklishin** [comment]
Yes, we'd be interested in having an easy way to use a modern standard HTTP client in the JDK (I am not sure if there is one but will assume at least something has changed since JDK 8). Fewer dependencies would be appealing to some users.

**Comment by michaelklishin** [comment]
That said if we learn that it is too hard to remove the implicit dependency, the current state of things that make using one of the two popular clients would be plenty sufficient for me.

**Pull request merged**
