### PR TITLE
Make Java 6 as minimal

### PR DESCRIPTION
**Pull request by artembilan**
Mark `"PUT /api/vhosts/{name}"` with `@IgnoreIf({ os.windows })`

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

**Comment by artembilan** [comment]
I think the issue with Windows because it uses `CP1251` encoding. Hence it is used from my local RabbitMQ.
We send data from our test in `UTF-8`, hence they are encoded on RabbitMQ (or Mochiweb) incorrectly.
WDYT?

**Comment by michaelklishin** [comment]
We can mess with `file.encoding` but this test isn't particularly important for the client. It was originally added in the Ruby client in the early `cf-rabbitmq` days just to be sure that vhost names with non-ASCII characters work as expected.

Not only we run this test in *nix environments (which is what RabbitMQ team uses 90% of the time), it tests virtually nothing in the actual client.

Feel free to look into making it pass on Windows but I'd rather spend your time on something else.

**Comment by artembilan** [comment]
OK. Let's live with that!

I think now @garyrussell 's wrapper would be very simple.
There is just need to work off Bamboo plan and add this dep to our Spring AMQP.

**Comment by michaelklishin** [comment]
Cool. I'd publish a `beta1` release for now and release `1.0.0` when we document the library (and make a decision on release synchronisation with RabbitMQ). Would that work for Spring AMQP?

**Comment by artembilan** [comment]
I think so.
Do you need CI plan to push the `B-S` to Spring repo?
Or do we wait for your talk with Gary?
Can I join, BTW?
As I understand you are Ukrainian natively

**Comment by michaelklishin** [comment]
We currently use Travis for CI. We can add a CI plan on Bamboo but I'm not familiar with how Spring projects are built and integrated to suggest how much sense it would make. We'll send you an invite
to a call to discuss that but we haven't scheduled anything yet.

I am a Russia national. Not that it matters.

**Pull request merged**
