### PR TITLE
Remove zeroed sockets_used/sockets_total

### PR DESCRIPTION
**Pull request by lhoguin**
Values are zeroed following partial removal of the FHC.

FYI I don't know what I'm doing. This is Java or something. Let's see if it works!

### CODE REVIEW

**Comment by lhoguin** [comment]
@acogoluegnes Can you help? Thanks!

**Comment by michaelklishin** [comment]
It was a matter of removing a couple more methods in `NodeInfo.java`.

**Comment by lhoguin** [comment]
Huh. My bad, I thought I had covered them all. Thanks for the fix!

**Comment by acogoluegnes** [comment]
See https://github.com/rabbitmq/rabbitmq-server/pull/11436.

**Pull request merged**
